### PR TITLE
Update forge_java_error.json

### PR DESCRIPTION
**Pull request by forkiesassds**

### CODE REVIEW

**Comment by JustDoom** [comment]
Why anything above 9? Last time I checked Java 11 works fine with forge

**Comment by forkiesassds** [comment]
Last time I tried running Forge 1.2.5 on Java 9+ it didn't work.

**Comment by JustDoom** [comment]
Ah makes sense for older versions, I was thinking 1.12 and above. Ill add a note about older versions

**Comment by JustDoom** [comment]
https://github.com/Eimer-Archive/MineCrashSolutions/commit/ff13eec91bb2f0ddfe7e5348fe9e0149e2cae33a

**Pull request closed without merging**
